# Programming Assignment 5
---
**Author:** Yeva Kramarova  
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**

- Problem 1: Language Translator.
- Problem 2: Translating Morse Code.
- Problem 3: Comparing Minors/Majors.
- Problem 4: Working with NumPy.

### Problem 1 - Language Translator

In [1]:

translation_dict = {
    "couch": "диван",
    "chair": "стільчик",
    "man": "чоловік",
    "woman": "жінка",
    "bear": "ведмідь",
    "cat": "кіт",
    "dog": "собака"
}

while True:
    word = input("Enter a word to translate from English to Ukrainian (enter 0 to stop): ").lower()
    if word == "0":
        break
    elif word in translation_dict:
        print(f"The Ukrainian word for {word.upper()} is {translation_dict[word].upper()}.")
    else:
        print(f"The Ukrainian word for {word.upper()} is not in this dictionary.")


Enter a word to translate from English to Ukrainian (enter 0 to stop):  couch


The Ukrainian word for COUCH is ДИВАН.


Enter a word to translate from English to Ukrainian (enter 0 to stop):  dog


The Ukrainian word for DOG is СОБАКА.


Enter a word to translate from English to Ukrainian (enter 0 to stop):  chair


The Ukrainian word for CHAIR is СТІЛЬЧИК.


Enter a word to translate from English to Ukrainian (enter 0 to stop):  man


The Ukrainian word for MAN is ЧОЛОВІК.


Enter a word to translate from English to Ukrainian (enter 0 to stop):  woman


The Ukrainian word for WOMAN is ЖІНКА.


Enter a word to translate from English to Ukrainian (enter 0 to stop):  bear


The Ukrainian word for BEAR is ВЕДМІДЬ.


Enter a word to translate from English to Ukrainian (enter 0 to stop):  cat


The Ukrainian word for CAT is КІТ.


Enter a word to translate from English to Ukrainian (enter 0 to stop):  0


### Problem 2 - Translating Morse Code

In [2]:

morse_code_dict = {
    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....', 'I': '..', 
    'J': '.---', 'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.', 
    'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-', 'Y': '-.--', 'Z': '--..',
    '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....', '6': '-....', '7': '--...', 
    '8': '---..', '9': '----.'
}

def translate_to_morse(sentence):
    morse_code = ''
    for char in sentence.upper():
        if char.isalnum():
            morse_code += morse_code_dict[char] + ' '
    return morse_code.strip()

while True:
    message = input("Enter a sentence to translate to Morse Code (enter 'q' to quit): ")
    if message.lower() == 'q':
        break
    else:
        print("Morse Code Translation:", translate_to_morse(message))


Enter a sentence to translate to Morse Code (enter 'q' to quit):  AB


Morse Code Translation: .- -...


Enter a sentence to translate to Morse Code (enter 'q' to quit):  HELLO


Morse Code Translation: .... . .-.. .-.. ---


Enter a sentence to translate to Morse Code (enter 'q' to quit):  HOW ARE YOU


Morse Code Translation: .... --- .-- .- .-. . -.-- --- ..-


Enter a sentence to translate to Morse Code (enter 'q' to quit):  q


### Problem 3 - Comparing Minors/Majors

In [3]:
cs_minor = {'CS130', 'CS131', 'CS215', 'CS305', 'CS310', 'CS330'}
bus_adm_minor = {'BUSA103', 'BUSA203', 'BUSA305', 'MATH125', 'ACCT101', 'ECON110'}
bus_anl_minor = {'BUSA103', 'BUSA245', 'BUSA346', 'CS150', 'DS160', 'DS300'}
ds_major = {'BUSA103', 'BUSA245', 'BUSA346', 'CS150', 'DS160', 'DS300'}

overlap_courses = bus_adm_minor.intersection(bus_anl_minor)
print("Courses overlapping between Business Administration and Business Analytics minors:", overlap_courses)

courses_required = bus_adm_minor.union(cs_minor)
print("Courses required for students minoring in Business Administration and Computer Science:", courses_required)

courses_only_in_bus_adm = bus_adm_minor.difference(bus_anl_minor)
print("Courses only in Business Administration minor:", courses_only_in_bus_adm)

no_overlap = cs_minor.isdisjoint(ds_major)
print("No overlapping courses between Computer Science major and Data Science major:", no_overlap)

subsumed = bus_anl_minor.issubset(ds_major)
print("Business Analytics minor completely subsumed by Data Science major:", subsumed)
 

Courses overlapping between Business Administration and Business Analytics minors: {'BUSA103'}
Courses required for students minoring in Business Administration and Computer Science: {'CS310', 'BUSA103', 'CS130', 'MATH125', 'BUSA305', 'ECON110', 'ACCT101', 'CS215', 'CS131', 'BUSA203', 'CS305', 'CS330'}
Courses only in Business Administration minor: {'MATH125', 'BUSA305', 'ECON110', 'ACCT101', 'BUSA203'}
No overlapping courses between Computer Science major and Data Science major: True
Business Analytics minor completely subsumed by Data Science major: True


### Problem 4 - Working with NumPy

In [4]:
import numpy as np

array1 = np.random.randint(0, 21, size=(5, 5))
array2 = np.random.randint(0, 21, size=(5, 5))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

matrix_product = np.matmul(array1, array2)
dot_product = np.dot(array1.flatten(), array2.flatten())

print("\nMatrix Product:")
print(matrix_product)
print("\nDot Product:")
print(dot_product)

det_array1 = np.linalg.det(array1)
inv_array1 = np.linalg.inv(array1)
det_array2 = np.linalg.det(array2)
inv_array2 = np.linalg.inv(array2)

print("\nDeterminant of Array 1:", det_array1)
print("Inverse of Array 1:")
print(inv_array1)
print("\nDeterminant of Array 2:", det_array2)
print("Inverse of Array 2:")
print(inv_array2)

array1d_1 = np.linspace(0, 1, 20)
array1d_2 = np.linspace(1, 2, 20)

combined_array = np.concatenate((array1d_1, array1d_2))

reshaped_array = np.reshape(combined_array, (10, 4))

print("\nCombined 2D Array:")
print(reshaped_array)


Array 1:
[[18 18 17 14  5]
 [17  0 10 17 13]
 [ 4  0  1  9 17]
 [ 4  7 14 12 11]
 [ 5 19  5 10  5]]

Array 2:
[[ 0  3 10  6 18]
 [ 2 19  2  6 14]
 [ 2  0 12 12  9]
 [19 16  4 10  8]
 [ 3 13 13  1  2]]

Matrix Product:
[[351 685 541 565 851]
 [382 492 527 405 558]
 [224 377 309 143 187]
 [303 480 413 365 414]
 [253 601 253 309 491]]

Dot Product:
1816

Determinant of Array 1: -326344.00000000006
Inverse of Array 1:
[[ 0.08465913 -0.0084175   0.04959491 -0.08254786 -0.04979102]
 [ 0.0331552  -0.04582588  0.02973856 -0.01984103  0.02853124]
 [ 0.04781458 -0.0452927  -0.00470975  0.07166364 -0.07170041]
 [-0.16029711  0.15177849 -0.13961954  0.04832937  0.13405486]
 [ 0.06213076 -0.07570845  0.12134741 -0.01037862 -0.05503702]]

Determinant of Array 2: -721979.9999999998
Inverse of Array 2:
[[ 0.03926702 -0.05901272 -0.0429818   0.06352531 -0.00099726]
 [-0.03664921  0.04936425 -0.00094185 -0.00891991  0.0242112 ]
 [ 0.02225131 -0.03915482  0.00865952 -0.00622455  0.05975235]
 [-0.08769634